TTAA_codition = {
    "G1_99":{
             "g_idx":"99",
             "press":"",
             "press_pos":[2,5],
             "press_add":["1",""],
             "height":"0",
             "h_pos":["",""],
             "h_add":["",""]
             },
    "G2_00":{
             "g_idx":"00",
             "press":"",
             "press_pos":[0,3],
             "press_add":["1",""],
             "height":"",
             "h_pos":[3,5],
             "h_add":["1",""]
             },
    "G3_92":{
             "g_idx":"92",
             "press":"925",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["",""]
            },
    "G4_85":{
             "g_idx":"85",
             "press":"850",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["1",""]
            },
    "G5_70":{
             "g_idx":"70",
             "press":"700",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["3",""]
            },
    "G6_50":{
             "g_idx":"50",
             "press":"500",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["","0"]
            },
    "G7_40":{
             "g_idx":"40",
             "press":"400",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["","0"]
            },
    "G8_30":{
             "g_idx":"30",
             "press":"300",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["","0"]
            },
    "G9_25":{
             "g_idx":"25",
             "press":"250",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["1","0"]
            },
    "G10_20":{
             "g_idx":"20",
             "press":"200",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["1","0"]
            },
    "G11_15":{
             "g_idx":"15",
             "press":"150",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["1","0"]
            },
    "G12_10":{
             "g_idx":"10",
             "press":"100",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["1","0"]
            },
    "G13_88":{
             "g_idx":"88",
             "press":"",
             "press_pos":[2,5],
             "press_add":["",""],
             "height":"18288",
             "h_pos":["",""],
             "h_add":["",""]
            }

}

TTCC_codition = {
     "G1_70":{
             "g_idx":"70",
             "press":"70",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["1","0"]
             },
    "G2_50":{
             "g_idx":"50",
             "press":"50",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["2","0"]
             },
    "G3_30":{
             "g_idx":"30",
             "press":"30",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["2","0"]
             },
    "G4_88":{
             "g_idx":"88",
             "press":"10",
             "press_pos":["",""],
             "press_add":["",""],
             "height":"",
             "h_pos":[2,5],
             "h_add":["3","0"]
             }
}

